-- Create Warehouse
CREATE OR REPLACE WAREHOUSE DEMO_WH 
  WITH WAREHOUSE_SIZE = 'XSMALL' 
  AUTO_SUSPEND = 300 
  AUTO_RESUME = TRUE;

USE WAREHOUSE DEMO_WH;

-- Create Database and Schema
CREATE OR REPLACE DATABASE DEMO_DB;
USE DATABASE DEMO_DB;

CREATE OR REPLACE SCHEMA DEMO_SCHEMA;
USE SCHEMA DEMO_SCHEMA


-- Create Table
CREATE OR REPLACE TABLE EMPLOYEES (
    EMP_ID INT,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    DEPARTMENT VARCHAR(50),
    SALARY NUMBER(10,2)
);

-- Create Internal Stage
CREATE OR REPLACE STAGE MY_INTERNAL_STAGE;


-- INSERT
INSERT INTO EMPLOYEES (EMP_ID, FIRST_NAME, LAST_NAME, DEPARTMENT, SALARY) 
VALUES 
    (101, 'Alice', 'Smith', 'HR', 60000),
    (102, 'Bob', 'Jones', 'IT', 75000),
    (103, 'Charlie', 'Brown', 'Finance', 80000);

-- SELECT
SELECT * FROM EMPLOYEES;

-- UPDATE
UPDATE EMPLOYEES 
SET SALARY = 65000 
WHERE EMP_ID = 101;

-- DELETE
DELETE FROM EMPLOYEES 
WHERE EMP_ID = 103;

-- Final Check
SELECT * FROM EMPLOYEES;



-- TIME TRAVEL IN SNOWFLAKE
CREATE OR REPLACE TABLE TT_DEMO (
    ID INT,
    STATUS VARCHAR(20)
);

INSERT INTO TT_DEMO VALUES (1, 'Active'), (2, 'Pending'), (3, 'Active');

-- Capture baseline timestamp before modifications
SELECT CURRENT_TIMESTAMP();
-- Note down the returned timestamp (e.g., 2026-09-15 10:00:00.000 +0000)

UPDATE TT_DEMO SET STATUS = 'Inactive' WHERE ID = 1;
DELETE FROM TT_DEMO WHERE ID = 3;

-- Query current modified state
SELECT * FROM TT_DEMO;

-- Query state from 5 minutes ago using OFFSET
SELECT * FROM TT_DEMO AT(OFFSET => -60*5);

-- OR query using your recorded timestamp
SELECT * FROM TT_DEMO AT(TIMESTAMP => '2026-09-15 10:00:00.000 +0000'::TIMESTAMP_TZ);

-- DATA RECOVERY

-- Delete records
DELETE FROM EMPLOYEES WHERE DEPARTMENT = 'IT';

-- Save statement ID of the DELETE operation
SET delete_query_id = LAST_QUERY_ID();

-- Verify records are gone from current view
SELECT * FROM EMPLOYEES WHERE DEPARTMENT = 'IT';


-- VIEW DELETED DATA
SELECT * FROM EMPLOYEES BEFORE(STATEMENT => $delete_query_id)
WHERE DEPARTMENT = 'IT';

-- RESTORE DELETED RECORDS
INSERT INTO EMPLOYEES
SELECT * FROM EMPLOYEES BEFORE(STATEMENT => $delete_query_id)
WHERE DEPARTMENT = 'IT';

SELECT * FROM EMPLOYEES WHERE DEPARTMENT = 'IT';
